using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using FluentAssertions;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.Configuration;

namespace Tracer.Infrastructure.Tests.OpenApi;

/// <summary>
/// Verifies that the OpenAPI document generated by
/// <c>Tracer.Api.OpenApi.TracerOpenApiDocumentTransformer</c> and
/// <c>Tracer.Api.OpenApi.ApiKeySecurityRequirementTransformer</c>
/// reflects the contract described in B-82:
/// Info block is populated, the <c>ApiKey</c> security scheme is registered,
/// every operation advertises the requirement except the anonymous allowlist
/// (<c>/health</c>, <c>/openapi/*</c>), and the Scalar UI is mount-gated.
/// </summary>
public sealed class OpenApiDocumentTests
{
    private const string TestApiKey = "test-api-key-openapi";

    private static WebApplicationFactory<Program> CreateFactory(bool enableUi = true)
    {
        #pragma warning disable CA2000 // factory disposed by caller
        return new WebApplicationFactory<Program>()
            .WithWebHostBuilder(builder =>
            {
                builder.ConfigureAppConfiguration((_, config) =>
                {
                    // Non-empty connection string prevents Program.cs from throwing at boot.
                    // The DB is never touched by OpenAPI document tests.
                    config.AddInMemoryCollection(new Dictionary<string, string?>
                    {
                        ["ConnectionStrings:TracerDb"] = "Server=(localdb)\\mssqllocaldb;Database=TracerTest;",
                        ["Auth:ApiKeys:0"] = TestApiKey,
                        ["OpenApi:Title"] = "Tracer API",
                        ["OpenApi:Version"] = "v1",
                        ["OpenApi:Description"] = "Company enrichment engine for FieldForce.",
                        ["OpenApi:ContactName"] = "FieldForce Platform Team",
                        ["OpenApi:ContactEmail"] = "platform@example.com",
                        ["OpenApi:LicenseName"] = "Proprietary",
                        ["OpenApi:EnableUi"] = enableUi.ToString(),
                        ["Revalidation:Enabled"] = "false",
                    });
                });

                builder.ConfigureTestServices(services =>
                {
                    // Polly SamplingDuration >= 2x AttemptTimeout — same guard as other
                    // WebApplicationFactory-based tests.
                    services.ConfigureAll<Microsoft.Extensions.Http.Resilience.HttpStandardResilienceOptions>(
                        options => options.CircuitBreaker.SamplingDuration = TimeSpan.FromMinutes(2));
                });
            });
        #pragma warning restore CA2000
    }

    private static async Task<JsonDocument> FetchSpecAsync(WebApplicationFactory<Program> factory)
    {
        using var client = factory.CreateClient();
        // Spec endpoint is explicitly anonymous; no X-Api-Key header required.
        using var response = await client.GetAsync(new Uri("/openapi/v1.json", UriKind.Relative))
            .ConfigureAwait(false);
        response.StatusCode.Should().Be(HttpStatusCode.OK);
        response.Content.Headers.ContentType?.MediaType.Should().Be("application/json");

        var stream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);
        return await JsonDocument.ParseAsync(stream).ConfigureAwait(false);
    }

    [Fact]
    public async Task OpenApiSpec_IsServed_WithConfiguredInfoBlock()
    {
        var factory = CreateFactory();
        await using (factory.ConfigureAwait(true))
        {
            using var document = await FetchSpecAsync(factory).ConfigureAwait(true);

            var info = document.RootElement.GetProperty("info");
            info.GetProperty("title").GetString().Should().Be("Tracer API");
            info.GetProperty("version").GetString().Should().Be("v1");
            info.GetProperty("description").GetString()
                .Should().Contain("Company enrichment engine", because: "Info.Description is projected from configuration");

            var contact = info.GetProperty("contact");
            contact.GetProperty("name").GetString().Should().Be("FieldForce Platform Team");
            contact.GetProperty("email").GetString().Should().Be("platform@example.com");

            info.GetProperty("license").GetProperty("name").GetString().Should().Be("Proprietary");
        }
    }

    [Fact]
    public async Task OpenApiSpec_RegistersApiKeySecurityScheme_WithXApiKeyHeader()
    {
        var factory = CreateFactory();
        await using (factory.ConfigureAwait(true))
        {
            using var document = await FetchSpecAsync(factory).ConfigureAwait(true);

            var schemes = document.RootElement
                .GetProperty("components")
                .GetProperty("securitySchemes");
            schemes.TryGetProperty("ApiKey", out var apiKey).Should().BeTrue(
                because: "TracerOpenApiDocumentTransformer must register the ApiKey scheme");

            apiKey.GetProperty("type").GetString().Should().Be("apiKey");
            apiKey.GetProperty("in").GetString().Should().Be("header");
            apiKey.GetProperty("name").GetString().Should().Be("X-Api-Key");
        }
    }

    [Fact]
    public async Task OpenApiSpec_ProtectedOperations_HaveApiKeyRequirement()
    {
        var factory = CreateFactory();
        await using (factory.ConfigureAwait(true))
        {
            using var document = await FetchSpecAsync(factory).ConfigureAwait(true);

            var paths = document.RootElement.GetProperty("paths");
            var protectedPaths = new[]
            {
                "/api/trace",
                "/api/trace/{traceId}",
                "/api/trace/batch",
                "/api/profiles",
                "/api/profiles/{profileId}",
                "/api/changes",
                "/api/changes/stats",
                "/api/stats",
            };

            foreach (var path in protectedPaths)
            {
                paths.TryGetProperty(path, out var pathItem).Should().BeTrue(
                    because: $"expected path '{path}' to be registered");

                foreach (var operation in pathItem.EnumerateObject())
                {
                    // Skip non-operation properties (parameters, summary).
                    if (!OperationMethods.Contains(operation.Name, StringComparer.OrdinalIgnoreCase))
                        continue;

                    operation.Value.TryGetProperty("security", out var security).Should().BeTrue(
                        because: $"{operation.Name.ToUpperInvariant()} {path} is protected and must advertise the ApiKey requirement");

                    security.EnumerateArray()
                        .Any(req => req.TryGetProperty("ApiKey", out _))
                        .Should().BeTrue(because: $"{operation.Name.ToUpperInvariant()} {path} must reference the ApiKey scheme");
                }
            }
        }
    }

    [Fact]
    public async Task OpenApiSpec_ListsFourTagsWithDescriptions()
    {
        var factory = CreateFactory();
        await using (factory.ConfigureAwait(true))
        {
            using var document = await FetchSpecAsync(factory).ConfigureAwait(true);

            var tags = document.RootElement.GetProperty("tags").EnumerateArray().ToList();
            var tagNames = tags
                .Select(t => t.GetProperty("name").GetString())
                .Where(n => n is not null)
                .Select(n => n!)
                .ToList();

            tagNames.Should().Contain("Trace")
                .And.Contain("Profiles")
                .And.Contain("Changes")
                .And.Contain("Stats");

            foreach (var tag in tags)
            {
                tag.GetProperty("description").GetString().Should().NotBeNullOrWhiteSpace();
            }
        }
    }

    [Fact]
    public async Task ScalarUi_IsReachable_WhenEnableUiTrue()
    {
        var factory = CreateFactory(enableUi: true);
        await using (factory.ConfigureAwait(true))
        {
            using var client = factory.CreateClient();
            using var response = await client.GetAsync(new Uri("/scalar/v1", UriKind.Relative))
                .ConfigureAwait(true);

            // Scalar responds with an HTML page; some versions redirect first — accept either.
            response.StatusCode.Should().BeOneOf(
                HttpStatusCode.OK,
                HttpStatusCode.Redirect,
                HttpStatusCode.Found,
                HttpStatusCode.PermanentRedirect);
        }
    }

    [Fact]
    public async Task ScalarUi_IsNotMounted_WhenEnableUiFalseInProductionLikeHost()
    {
        // Disable EnableUi; WebApplicationFactory defaults to Development environment,
        // so the factory is in dev mode — Scalar is still mounted (dev pass-through).
        // The UI gating behaviour is therefore asserted only via the dev override path;
        // a production-mode run is covered by forcing the environment name below.
        using var factory = new WebApplicationFactory<Program>()
            .WithWebHostBuilder(builder =>
            {
                builder.UseEnvironment("Production");
                builder.ConfigureAppConfiguration((_, config) =>
                {
                    config.AddInMemoryCollection(new Dictionary<string, string?>
                    {
                        ["ConnectionStrings:TracerDb"] = "Server=(localdb)\\mssqllocaldb;Database=TracerTest;",
                        ["Auth:ApiKeys:0"] = TestApiKey,
                        ["Cors:AllowedOrigins:0"] = "https://example.com",
                        ["OpenApi:EnableUi"] = "false",
                        ["Revalidation:Enabled"] = "false",
                    });
                });
                builder.ConfigureTestServices(services =>
                {
                    services.ConfigureAll<Microsoft.Extensions.Http.Resilience.HttpStandardResilienceOptions>(
                        options => options.CircuitBreaker.SamplingDuration = TimeSpan.FromMinutes(2));
                });
            });

        using var client = factory.CreateClient();
        using var response = await client.GetAsync(new Uri("/scalar/v1", UriKind.Relative))
            .ConfigureAwait(true);

        response.StatusCode.Should().Be(HttpStatusCode.NotFound,
            because: "Scalar UI must not be mounted in Production hosts unless OpenApi:EnableUi=true");
    }

    private static readonly HashSet<string> OperationMethods = new(StringComparer.OrdinalIgnoreCase)
    {
        "get", "post", "put", "patch", "delete", "head", "options", "trace",
    };
}
